### ISSUE TITLE
GCC问题修复

### ISSUE THREAD

**Issue by LCAR979** [LCAR979/HPC_wiki_docs#14]
##  问题：
master gcc缺失， node1~6默认的gcc不一样, 2/4为4.8.2, 1/3/5/6 为4.4.7 (node2/4的/usr/bin/gcc为软链接指向了/opt/rh/...gcc)

- [x]  修复
    - node2/4和master均已修复， 三者的/usr/bin/gcc 现在均为原系统的gcc-4.4 
    -  (master原始gcc的可执行文件丢失，scp自node1:/usr/bin/gcc)
    -  g++ 行为一致, 在Master和node2/4已经进行了完整测试：原生gcc 为4.4， module load后为gcc 4.8，符合期望
- [x] 文档
      - 使用gcc-4.8的情景应当推荐统一使用module gcc    
      - 文档中加入介绍 gcc的一个小节

**Comment by yingjieyao** [comment]
刚看了一下，node1/3/5/6并没有安装gcc-4.8.2；
当初这个东西是来自于devtoolset-2的，我再找找
