### ISSUE TITLE
`Version 'GLIBC_2.14' not found ` Solution

### ISSUE THREAD

**Issue by LCAR979** [LCAR979/HPC_wiki_docs#18]
Contributed by @sonack and @CastellanLiu  

![image](https://user-images.githubusercontent.com/7692262/44245603-1a56bf00-a20c-11e8-8cb5-ffb44009eb69.png)

~~1. cp -R /share/package/glibc/glibc-2.14 $HOME/glibc-2.14-src
2. cd $HOME/glibc-2.14-src
3. mkdir build && cd build 
4. ../configure --prefix=$HOME/glibc-2.14
5. make -j4 && make install 
6. [After installation] 
export LD_LIBRARY_PATH=/path_to_glibc/lib:$LD_LIBRARY_PATH~~

export LD_PRELOAD=/path_to_glibc/lib/libc.so.6:$LD_PRELOAD
[src](https://www.linuxidc.com/Linux/2017-01/139806.htm)

**Comment by LCAR979** [comment]
Todo: 在/share/package下放入glibc-2.14的解压源码，供复制用。

**Comment by LCAR979** [comment]
DONE

**Comment by yhldhit** [comment]
有个小问题， LD_LIBRARY_PATH 对应的目录lib不是bin

**Comment by LCAR979** [comment]
以下测试需要先加载虚拟环境。
```
module load conda 
source activate py36pytorch0.4.0
```

为了修复新出现的GLIBC-2.14导致的虚拟环境无法使用问题，我把glibc2.14编译安装到了/share/apps/glibc2.14，这样就不需要每个人在自己目录手动编译glibc。之后：

方案一. 不用patchelf修改某个环境下的python解释器二进制文件, 通过命令行调用ld-2.14.so，给出library-path 再调用python
```
export GLIBC_DIR=/share/apps/glibc-2.14/lib                                                            
$GLIBC_DIR/ld-2.14.so --library-path $GLIBC_DIR:/lib64:$LD_LIBRARY_PATH `which python` demo.py
```

方案二, 用patchelf修改某个环境下的python解释器二进制文件

修改过程
```
cd /share/apps/anaconda2/envs/py36pytorch0.4.0/bin/   
cp python3.6 python3.6.bak  # backup 
patchelf --set-interpreter /share/apps/glibc-2.14/lib/ld-linux-x86-64.so.2 python3.6
readelf -l python3.6  #changes should be seen 
```
程序运行：
```
python demo.py
```

测试不用GPU和任务调度的简单PyTorch程序。方案一可以，之后用patchelf修改，方案二也可以。希望大家做一下进一步的测试（目前`anaconda2/envs/py36pytorch0.4.0/bin` 下面的python3.6是fix过elf的,使用方案二来调用测试），包括使用任务系统、复杂程序。

**Comment by LCAR979** [comment]
目前发现使用这两个方案可能导致cuda加载错误，报错`cuda driver version is insufficient for cuda runtime version`. 对于pytorch0.4.1,使用之前的`LD_PRELOAD`则不会。

**Comment by LCAR979** [comment]
在服务器上拉取了glibc分支a7da90e，发布到线上，等待后续观察处理
